# User defined entries should be added to this file not to /etc/sysctl.d/* as
# that directory is not backed-up by default and will not survive a reimage

# Increase socket buffer defaults for multi-VAP WiFi devices
net.core.rmem_default=524288
net.core.wmem_default=524288
